In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
## sentence
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good developer',
    'understanding the meaning of words',
    'your videos are good',
]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good developer',
 'understanding the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size 
voc_size=10000

In [8]:
## one hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[796, 9330, 5508, 124],
 [796, 9330, 5508, 9285],
 [796, 344, 5508, 8590],
 [3112, 5435, 7674, 7160, 5554],
 [1243, 796, 7154, 5508, 3280],
 [1774, 3631, 8470, 7160]]

In [9]:
## word embedding Representation

from tensorflow.keras.layers import Embedding 
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [10]:
import numpy as np

In [11]:
sent_length = 8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0  796 9330 5508  124]
 [   0    0    0    0  796 9330 5508 9285]
 [   0    0    0    0  796  344 5508 8590]
 [   0    0    0 3112 5435 7674 7160 5554]
 [   0    0    0 1243  796 7154 5508 3280]
 [   0    0    0    0 1774 3631 8470 7160]]


In [12]:
## feature reprenetation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 20ms/step


array([[ 0.00256116,  0.04753057,  0.04783863,  0.02355507, -0.00418573,
        -0.02987833,  0.02018856, -0.00811797, -0.02902373,  0.04652785],
       [ 0.00256116,  0.04753057,  0.04783863,  0.02355507, -0.00418573,
        -0.02987833,  0.02018856, -0.00811797, -0.02902373,  0.04652785],
       [ 0.00256116,  0.04753057,  0.04783863,  0.02355507, -0.00418573,
        -0.02987833,  0.02018856, -0.00811797, -0.02902373,  0.04652785],
       [ 0.00256116,  0.04753057,  0.04783863,  0.02355507, -0.00418573,
        -0.02987833,  0.02018856, -0.00811797, -0.02902373,  0.04652785],
       [ 0.0470178 , -0.03091234, -0.04346193,  0.0055664 ,  0.0336298 ,
        -0.00230434,  0.03088537, -0.00919346, -0.00360781,  0.04829613],
       [-0.01804278,  0.04821516, -0.03813352,  0.03879846,  0.03403732,
        -0.04133616,  0.01177847, -0.02548893, -0.02737864,  0.02203835],
       [ 0.03311782,  0.00426393, -0.04863599, -0.04077375, -0.00332776,
         0.03212792,  0.04160165,  0.0387569 

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0,  796, 9330, 5508,  124], dtype=int32)